> Benjamin Nikholas

> Data Science / JCSDOL-014

> Modul 2 - Tugas 17

> 3 Juni 2024
---
---

In [2]:
import numpy as np
import pandas as pd

# 1
 Buatlah sebuah array 1 dimensi (vektor) yang diisi dengan 36 elemen. Isi dari array
tersebut adalah bilangan random yang dibangkitkan dari rentang nilai 1 hingga 100.
Simpan array tersebut dalam sebuah variable bernama myArray, kemudian coba
tampilkan!


In [3]:
myArray = np.random.randint(1, 101, size=36)
print(myArray)

[ 67  10  25  36  49   2 100  94  81  32  10  91  70  45  40  65  41  28
  39  77  98  72  74  44  35  87  46  69   1  50  92  41  43  70  90  61]


# 2
 Dari myArray, bentuklah 3 array dengan bentuk yang berbeda (mengganti dimensi
matriksnya) dengan kombinasi ukuran yang berbeda beda!
* Matriks berukuran 2x18
* Matriks berukuran 9x4
* Array 3 Dimensi berukuran 2x6x3

In [4]:
shape_list = [(2, 18), (9, 4), (2, 6, 3)]
for i in shape_list:
  print(f'MyArray Reshape: {i}')
  print(myArray.reshape(i), '\n')

MyArray Reshape: (2, 18)
[[ 67  10  25  36  49   2 100  94  81  32  10  91  70  45  40  65  41  28]
 [ 39  77  98  72  74  44  35  87  46  69   1  50  92  41  43  70  90  61]] 

MyArray Reshape: (9, 4)
[[ 67  10  25  36]
 [ 49   2 100  94]
 [ 81  32  10  91]
 [ 70  45  40  65]
 [ 41  28  39  77]
 [ 98  72  74  44]
 [ 35  87  46  69]
 [  1  50  92  41]
 [ 43  70  90  61]] 

MyArray Reshape: (2, 6, 3)
[[[ 67  10  25]
  [ 36  49   2]
  [100  94  81]
  [ 32  10  91]
  [ 70  45  40]
  [ 65  41  28]]

 [[ 39  77  98]
  [ 72  74  44]
  [ 35  87  46]
  [ 69   1  50]
  [ 92  41  43]
  [ 70  90  61]]] 



# 3
Berapakah nilai minimun dan maksimum dari myArray? Tampilkan dan coba perlihatkan
nilai maksimum dan minimum tersebut ada pada indeks keberapa!

In [5]:
print(f'Nilai Minimum myArray bernilai {myArray.min()} dan berada pada indeks ke {np.where(myArray == myArray.min())}')
print(f'Nilai Maksimum myArray bernilai {myArray.max()} dan berada pada indeks ke {np.where(myArray == myArray.max())}')

Nilai Minimum myArray bernilai 1 dan berada pada indeks ke (array([28], dtype=int64),)
Nilai Maksimum myArray bernilai 100 dan berada pada indeks ke (array([6], dtype=int64),)


# 4
Buatlah sebuah array baru dari myArray dengan data yang diambil berasal dari index 3,
5, 30, 12, 15, 8, 24, 14, 22. Setelah itu, reshape bentuknya menjadi sebuah matrix
ukuran 3x3!

In [6]:
idx = [3, 5, 30, 12, 15, 8, 24, 14, 22]

newArray = myArray[idx]
newArray = newArray.reshape(3, 3)
newArray

array([[36,  2, 92],
       [70, 65, 81],
       [35, 40, 74]])

# 5  
Dari matrix yang dibuat pada nomor 4, tampilkan data yang nilainya lebih besar dari 50!

In [7]:
print(newArray[newArray > 50])

[92 70 65 81 74]


# 6
Buat sebuah array menggunkan salah satu method di numpy dengan output seperti di
bawah ini!

In [10]:
np.linspace(0, 100,
            num=5,
            dtype = int)

array([  0,  25,  50,  75, 100])

# 7
Buatlah sebuah array 2 dimensi dengan ukuran NxN di mana N nya adalah sebuah
inputan. Isi dari array tersebut seluruhnya adalah angka 8!

In [13]:
N = int(input("Masukkan ukuran N: "))

array_NxN = np.full((N, N), 8)
array_NxN

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

# 8
 Buatlah 2 buah array 2 dimensi seperti gambar di bawah ini, lalu simpan dalam variabel
bernama arrayA dan arrayB!

In [24]:
arrayA = np.linspace(1, 12,
                     num = 12,
                     dtype = int).reshape(3, 4)
print(arrayA)

arrayB = np.linspace(100, 400,
                     num = 4,
                     dtype = int).reshape(4,1)

print('\n', arrayB)

arrayC = np.vstack((arrayA,
                    arrayB.flatten()))

print('\n', arrayC)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 [[100]
 [200]
 [300]
 [400]]

 [[  1   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]
 [100 200 300 400]]


# 9
Dari arrayC, lakukan slicing agar menghasilkan array di bawah ini!

In [20]:
arrayC[1:3, 2:4]

array([[ 7,  8],
       [11, 12]])

# 10
Dari arrayC, lakukan indexing untuk mendapatkan angka 200!

In [72]:
arrayC[3,1]

200