## Numpy

In [1]:
import numpy as np

In [23]:
## Membuat array dg angka Random
np.random.rand(10)

array([0.38609897, 0.56261394, 0.25995996, 0.05500604, 0.82638421,
       0.38219533, 0.25334336, 0.66591792, 0.63569994, 0.83349638])

- Membuat angka random dari 0 - 1
- .rand(Jumlah) ==> Jumlah angka yg ingin dibuat
- Jumlah angka dalam .rand(jumlah) menunjukkan DIMENSI dari Array

In [24]:
np.random.rand(3, 3)

array([[0.57231789, 0.77256505, 0.22674672],
       [0.09563457, 0.00666493, 0.22582294],
       [0.77848472, 0.15219077, 0.3561914 ]])

In [26]:
np.random.rand(3, 2, 3)

array([[[0.70293455, 0.3213885 , 0.79968668],
        [0.53712216, 0.9640965 , 0.1952409 ]],

       [[0.48212344, 0.38965082, 0.13609495],
        [0.11193361, 0.98181152, 0.44921592]],

       [[0.7141802 , 0.48942779, 0.13550438],
        [0.5913379 , 0.71105961, 0.82705015]]])

In [27]:
np.random.rand(3, 2)

array([[0.12833143, 0.52721929],
       [0.58787272, 0.20213267],
       [0.91882694, 0.17809121]])

In [28]:
np.random.rand(3, 4) ## Angka pertama menunjukkan BARIS - index 0, angka kedua menunjukkan KOLOM - index - 1

array([[0.11679827, 0.66130018, 0.89190168, 0.57474607],
       [0.49297751, 0.83802206, 0.86857671, 0.99131337],
       [0.57471822, 0.68231691, 0.1222464 , 0.16301626]])

In [29]:
np.random.randn(15)

array([ 0.78397004,  0.81541523,  1.19930354, -0.79114801,  0.03609558,
       -1.51583419,  1.53225024, -1.55097098, -1.39728206,  0.07984884,
        1.15672348,  1.58930617, -1.0870109 , -1.00027927, -0.83406891])

In [30]:
np.random.randn(3, 4) ## random Normal

array([[-0.60566069, -1.25916251, -0.57838313,  1.6493605 ],
       [ 0.66548405, -0.58459028,  0.95863942,  0.88682998],
       [-2.27355693,  0.66487037, -0.93645675, -0.98111273]])

- Membuat angka random yg terdistribusi Normal - membentuk Bell shape
- Range  angka antara -3 s/d 3
- Angka kebanyakan di antara -1 - 0 - 1 (sekitar 68%)

In [ ]:
#pip3 install numpy

In [31]:
np.random.randint(50)

35

- Membuat angka Random - Integer
- .randint(NilaiPaling Rendah, NilaiPaling Tinggi, Jumlah)
- Jika hanya ada 1 angka, berarti itu nilai batas atas (High)
- Jika ada 2 angka, berarti itu nilai batas bawah (Low) dan batas atas (High)
- Jika Jumlah angka tidak ditentukan, akan menggunakan nilai Default = 1

In [90]:
np.random.randint(80, 90)

81

In [92]:
np.random.randint(10, 20, 25)
## Membuat angka random dari 10 - 20, sejumlah 25 angka

array([11, 11, 15, 14, 15, 13, 17, 17, 15, 14, 13, 11, 14, 15, 16, 17, 12,
       10, 13, 11, 15, 19, 15, 17, 12])

In [93]:
## Array Multidimensi - Matrix
A = [
[1,2,3],
[4,5,6],
[7,8,9]]

In [94]:
Mat = np.array(A)

In [109]:
B = [5, 8, 90, 12, 10.5]

In [110]:
Vect = np.array(B)

In [97]:
Mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [98]:
Vect

array([ 5,  8, 90, 12, 10])

In [99]:
type(Mat)

numpy.ndarray

In [100]:
type(Vect)

numpy.ndarray

In [101]:
Mat.ndim ## Melihat dimensi dari Array ==> 2 dimensi

2

In [102]:
Vect.ndim ## 1 dimensi

1

In [103]:
Mat.size ## untuk melihat ukuran/jumlah isi data dari Array = 9 

9

In [104]:
Vect.size

5

In [105]:
len(Mat)

3

In [106]:
len(Vect)
## Jika Array 1 dimensi, Nilai dari Len dan Size akan sama

5

In [107]:
Mat.dtype ## Melihat tipe data dalam Array --> hanya ada 1 tipe data

dtype('int32')

In [111]:
Vect.dtype

dtype('float64')

In [112]:
Vect

array([ 5. ,  8. , 90. , 12. , 10.5])

In [113]:
Mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [114]:
MatF = Mat.astype('float') ## Mengubah tipe data dari Array

In [115]:
float(20)
int('8')

8

In [116]:
MatF

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [117]:
MatF.dtype

dtype('float64')

- Array hanya dapat memiliki 1 tipe data, sehingga fungsi .astype() akan mengubah seluruh tipe data

================================================================================================

Cara mengakses Array
- Mengakses Array sama seperti akses List basic bahkan lebih fleksibel 

In [120]:
Num = np.arange(1, 16) ** 2

In [121]:
Num

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225])

In [122]:
## Akses menggunakan Indexing


In [123]:
Num[4]

25

In [124]:
Num[2]

9

In [125]:
Num[-1]

225

In [126]:
Num[18] ## akan error karena jumlah data 15, index max = 14

IndexError: index 18 is out of bounds for axis 0 with size 15

In [127]:
## Slicing
Num[2:5]

array([ 9, 16, 25])

In [128]:
Num[:4]

array([ 1,  4,  9, 16])

In [129]:
Num[4:]

array([ 25,  36,  49,  64,  81, 100, 121, 144, 169, 196, 225])

In [158]:
A = [
[1,2,3,4,5],
[6,7,8,9,10],
[11,12,13,14,15],
[16,17,18,19,20],
[21,22,23,24,25]]

In [159]:
MatA = np.array(A)

In [132]:
A

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]

In [133]:
MatA

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [134]:
MatA[0][2]  ### Akses index 0 (dimensi 1), dan Index ke 2 (dimensi 2)

3

In [136]:
A[0][2]

3

In [137]:
A[1][2]

8

In [138]:
MatA[1][2]

8

In [139]:
MatA[1, 2]

8

In [140]:
A[1, 2] ## akan error, karena Index untuk List basic python harus INteger

TypeError: list indices must be integers or slices, not tuple

In [141]:
MatA[:][2]

array([11, 12, 13, 14, 15])

In [142]:
MatA[2]

array([11, 12, 13, 14, 15])

In [143]:
MatA[:, 2]

array([ 3,  8, 13])

In [144]:
MatA

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [148]:
MatA[:][0]

array([1, 2, 3, 4, 5])

In [149]:
MatA[1]

array([ 6,  7,  8,  9, 10])

In [150]:
MatA[:][1]

array([ 6,  7,  8,  9, 10])

In [151]:
MatA[:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [160]:
MatA

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [161]:
MatA[:, 2]

array([ 3,  8, 13, 18, 23])

In [ ]:
## Akses Seluruh Baris (dimensi 1), Kemudian akses Index 2 untuk SETIAP Elemen (Baris)
- Jika menggunakan KOMA di dalam kurung siku
Nilai Sebelum KOMA berarti BARIS yg akan diakses
Nilai setelah KOMA berarti KOLOM yg akan diakses

In [162]:
MatA[:, 3]

array([ 4,  9, 14, 19, 24])

In [163]:
MatA[:, 4]

array([ 5, 10, 15, 20, 25])

In [164]:
MatA[1:4 , 3 ]
## Mengakses BARIS Index 1 - 3
## Mengakses KOLOM Index 3

array([ 9, 14, 19])

In [165]:
MatA[:3, 1:4]
## Akses BARIS Index awal - 2
## Akses KOLOM Index 1 - 3

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14]])

In [166]:
MatA[:2][2:4]

array([], shape=(0, 5), dtype=int32)

In [168]:
MatA[:2, 2:4]

array([[3, 4],
       [8, 9]])

In [177]:
S = [9, 60, 20, 25, 68, 10, 2, 2, 31, 56, 8, 60, 63, 75, 99]
data = np.array(S)

In [178]:
data

array([ 9, 60, 20, 25, 68, 10,  2,  2, 31, 56,  8, 60, 63, 75, 99])

In [179]:
len(data)

15

In [180]:
np.sort(data)

array([ 2,  2,  8,  9, 10, 20, 25, 31, 56, 60, 60, 63, 68, 75, 99])

In [176]:
(25+31)/2

28.0

In [172]:
np.mean(data) ### Untuk menghitung rata-rata

34.92857142857143

In [181]:
np.median(data) ### Untuk hitung Median - Nilai tengah ==> Q2  ==> 50%

31.0

In [182]:
np.percentile(data, 25) ## untuk menghitung percentile 25% ---> Q1

9.5

In [184]:
np.percentile(data, 75) ## untuk menghitung percentile 75% ---> Q3

61.5

In [185]:
np.max(data) ## menghitung nilai Maks

99

In [186]:
np.min(data) ## Menghitung nilai Min

2

In [187]:
np.argmax(data) ## Menampilkan INDEX dari nilai Maksimum

14

In [188]:
np.argmin(data) ## Menampilkan INDEX dari nilai Minimum

6

In [190]:
np.sort(data) ## Melakukan Pengurutan

array([ 2,  2,  8,  9, 10, 20, 25, 31, 56, 60, 60, 63, 68, 75, 99])

In [191]:
np.sort(data)[::-1]

array([99, 75, 68, 63, 60, 60, 56, 31, 25, 20, 10,  9,  8,  2,  2])